name: cheminfo_env3
channels:
  - conda-forge
dependencies:
  - wget
  - python=3.11
  - rdkit
  - scikit-learn
  - matplotlib
  - pandas
  - numpy
  - seaborn
  - nglview
  - biopython
  - jupyterlab
  - notebook
  - pdbfixer
  - openmm
  - openmmforcefields
  - mdanalysis
  - molscrub
  - openbabel
  - pip
  - pip:
      - py3Dmol
      - useful_rdkit_utils
      - mols2grid 
